package strajaguard

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Parity check for Qwen BPE tokenizer used by jailbreak2xl.
// Expected IDs are generated by HuggingFace AutoTokenizer for the same tokenizer.json.
func TestTokenizer_Qwen_Parity_HowAreYou(t *testing.T) {
	if os.Getenv("STRAJA_INTEGRATION") == "" {
		t.Skip("set STRAJA_INTEGRATION=1")
	}

	bundleRoot := filepath.Join(repoRoot(t), "intel", "strajaguard_v1_specialists")
	state, err := LoadBundleState(bundleRoot)
	if err != nil || state.CurrentVersion == "" {
		t.Skip("no bundle state/current version")
	}
	modelDir := filepath.Join(bundleRoot, state.CurrentVersion, "jailbreak2xl")
	ok, err := dirExists(modelDir)
	if err != nil || !ok {
		t.Skip("no jailbreak2xl dir")
	}

	tok, err := LoadTokenizerFromDir(modelDir)
	if err != nil {
		t.Fatalf("LoadTokenizerFromDir: %v", err)
	}

	tpl, err := os.ReadFile(filepath.Join(modelDir, "prompt_template.txt"))
	if err != nil {
		t.Fatalf("read template: %v", err)
	}
	prompt := strings.ReplaceAll(string(tpl), "{input}", "how are you?")

	ids, mask := tok.Encode(prompt, 256)
	active := 0
	for _, v := range mask {
		if v != 0 {
			active++
		}
	}
	got := ids[:active]

	// HF AutoTokenizer (Qwen/Qwen2.5-0.5B-Instruct) ids for prompt_template.txt with input "how are you?"
	want := []int64{
		151644, 8948, 198, 2610, 525, 264, 33365, 13, 17841, 448, 6896, 825, 3950, 25, 17540, 8960, 476, 64209, 624, 151645,
		198, 151644, 872, 198, 5158, 525, 498, 5267, 151645, 198, 151644, 77091, 198,
	}

	if len(got) != len(want) {
		t.Fatalf("active token count mismatch: got=%d want=%d got_prefix=%v", len(got), len(want), got[:min(len(got), 40)])
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("token mismatch at %d: got=%d want=%d (got_prefix=%v)", i, got[i], want[i], got[max(0, i-5):min(len(got), i+5)])
		}
	}
}

func dirExists(path string) (bool, error) {
	st, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return st.IsDir(), nil
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
